name: Website Uptime Check

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minutes
  workflow_dispatch:       # Allows manual run

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Check if site is up
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://grabmany.com | grep 200 || exit 1
